export const products = [
  {
    id: 1,
    title: "Adidas",
    price: 50000,
    stock: 2,
    description: "Campera premium de hombre",
    category: "masculino",
    img: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.sporting.com.ar%2Fsporting%2Findumentaria%2Fcamperas%2Foutdoor%3Fmap%3Dcategory-1%2Ccategory-2%2Ccategory-3%2Cdisciplina&psig=AOvVaw08y3pwMpQrAOpCnEm3_m7d&ust=1682540461694000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCIjt1-jtxf4CFQAAAAAdAAAAABAI",
  },
  {
    id: 2,
    title: "wilson advance",
    price: 14500,
    stock: 15,
    description: "Ultra livianas y cuentan con camara de aire",
    category: "masculino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430010/foc364fsakkzmausrovn.jpg",
  },
  {
    id: 3,
    title: "Puma",
    price: 19000,
    stock: 3,
    description:
      "Las clasicas zapatillas que van para cualquier momento del dia",
    category: "masculino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430165/images_lujpmr.jpg",
  },
  {
    id: 4,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "masculino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 5,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "femenino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 6,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "femenino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 7,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "femenino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 8,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "femenino",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 9,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "niños",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 10,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "niños",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 11,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "niños",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
  {
    id: 12,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "niños",
    img: "https://res.cloudinary.com/dnqfh2chg/image/upload/v1669430220/rtokwmt3j03bblbfhwhb.jpg",
  },
];
